### ISSUE TITLE
Dunno how to debug in Pycharm

### ISSUE THREAD

**Issue by jcohenadad** [exmakhina/distriploy#12]
When debugging Python scripts in Pycharm, i would usually:
- point to the script capturing the CLI arguments
  - the script usually contains a `if __name__ == "__main__":`
- add parameters on the Pycharm config

however, when i do that with this package, i get the following:
~~~
Connected to pydev debugger (build 191.7479.30)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/julien/code/distriploy/distriploy/__main__.py", line 8, in <module>
    from .distriploy import get_cfg, release, mirror, postrelease
ModuleNotFoundError: No module named '__main__.distriploy'; '__main__' is not a package
~~~

i set up like this:
- script name: `/Users/julien/code/distriploy/distriploy/__main__.py`

To overcome the problem, I've created [this script](https://github.com/neuropoly/distriploy/blob/master/distriploy/debuglaunch.py), but now the problem is that I cannot specify input arguments :sad 

Help appreciated...

**Comment by kousu** [comment]
This is because of the difficult module rules that changed in py3k. You can no longer reliably launch scripts from your project directly, because when you run a script directly python considers it to have a different module path (which is usually but *not* always the same as its file path) -- `__main__` -- and the module path determines how relative imports work.

One solution (which I think is taken by most projects) is to never use relative imports, precisely because of this.

Another is to always do `pip install -e` (or `python setup.py develop`) and never run the script directly: you should have a `distriploy` script installed elsewhere. If you run `which distriploy` you can find it. It's probably `/Users/julien/.local/bin/distriploy`, but it might be in a venv too. That's the script you should be feeding to pycharm.

For example, here's what `flake8` installed as for me:

```
[kousu@requiem ~]$ cat ~/.local/bin/flake8 
#!/usr/bin/python3.6
# -*- coding: utf-8 -*-
import re
import sys
from flake8.main.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by kousu** [comment]
If you can't find the wrapper script for some reason, you can probably just adopt its solution into `debuglaunch.py`: just overwrite `sys.argv[]`

I'm a bit unclear why `runpy` won't take your `argv`s. It seems like you should just be able to pass them as normal. But I'm not going to look too much more into this.

**Comment by kousu** [comment]
By the way, check out `breakpoint()`: https://docs.python.org/3/library/functions.html#breakpoint. You write it in to your code and then it drops you into a shell at each point you put it. Furthermore, it's moddable so I bet you pycharm will drop you into a GUI if you use it there. You can use that *instead* of running in debug mode, probably.

**Comment by jcohenadad** [comment]
> If you run which distriploy you can find it. It's probably /Users/julien/.local/bin/distriploy, but it might be in a venv too. That's the script you should be feeding to pycharm.

Ah! That works! 🎉  Thank you so much @kousu

**Comment by jcohenadad** [comment]
We can probably get rid of `debuglaunch.py` (ugly solution-- yours is way better)
